[project]
name = "smart-supply-chain-ai"
version = "0.1.0"
description = "Sistema Inteligente de Otimização de Estoque e Compras com Visão Computacional"
authors = [
    {name = "Roberto Rosário Balbinotti", email = "balbinotti@proton.me"},
]
dependencies = []
requires-python = ">=3.13"
readme = "README.md"
license = {text = "Creative Commons Attribution-NonCommercial 4.0 International"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
