[project]
name = "smart-supply-chain-ai"
version = "0.1.0"
description = "Sistema Inteligente de Otimização de Estoque e Compras com Visão Computacional"
authors = [
    {name = "Roberto Rosário Balbinotti", email = "balbinotti@proton.me"},
]
dependencies = ["pandas>=2.3.1", "numpy>=2.3.2", "scikit-learn>=1.7.1"]
requires-python = ">=3.13"
readme = "README.md"
license = {text = "Creative Commons Attribution-NonCommercial 4.0 International"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
